# Script for populating the database. You can run it as:
#
#     mix run priv/repo/seeds.exs
#
# Inside the script, you can read and write to any of your
# repositories directly:
#
#     League.Repo.insert!(%League.SomeSchema{})
#
# We recommend using the bang functions (`insert!`, `update!`
# and so on) as they will fail if something goes wrong.

alias League.Repo
alias League.Stats.{Champion, Item}

# Champions
Repo.insert!(%Champion{id: 1, name: "Annie", key: "Annie"})
Repo.insert!(%Champion{id: 2, name: "Olaf", key: "Olaf"})
Repo.insert!(%Champion{id: 3, name: "Galio", key: "Galio"})
Repo.insert!(%Champion{id: 4, name: "Twisted Fate", key: "TwistedFate"})
Repo.insert!(%Champion{id: 5, name: "Xin Zhao", key: "XinZhao"})
Repo.insert!(%Champion{id: 6, name: "Urgot", key: "Urgot"})
Repo.insert!(%Champion{id: 7, name: "LeBlanc", key: "Leblanc"})
Repo.insert!(%Champion{id: 8, name: "Vladimir", key: "Vladimir"})
Repo.insert!(%Champion{id: 9, name: "Fiddlesticks", key: "Fiddlesticks"})
Repo.insert!(%Champion{id: 10, name: "Kayle", key: "Kayle"})
Repo.insert!(%Champion{id: 11, name: "Master Yi", key: "MasterYi"})
Repo.insert!(%Champion{id: 12, name: "Alistar", key: "Alistar"})
Repo.insert!(%Champion{id: 13, name: "Ryze", key: "Ryze"})
Repo.insert!(%Champion{id: 14, name: "Sion", key: "Sion"})
Repo.insert!(%Champion{id: 15, name: "Sivir", key: "Sivir"})
Repo.insert!(%Champion{id: 16, name: "Soraka", key: "Soraka"})
Repo.insert!(%Champion{id: 17, name: "Teemo", key: "Teemo"})
Repo.insert!(%Champion{id: 18, name: "Tristana", key: "Tristana"})
Repo.insert!(%Champion{id: 19, name: "Warwick", key: "Warwick"})
Repo.insert!(%Champion{id: 20, name: "Nunu & Willump", key: "Nunu"})
Repo.insert!(%Champion{id: 21, name: "Miss Fortune", key: "MissFortune"})
Repo.insert!(%Champion{id: 22, name: "Ashe", key: "Ashe"})
Repo.insert!(%Champion{id: 23, name: "Tryndamere", key: "Tryndamere"})
Repo.insert!(%Champion{id: 24, name: "Jax", key: "Jax"})
Repo.insert!(%Champion{id: 25, name: "Morgana", key: "Morgana"})
Repo.insert!(%Champion{id: 26, name: "Zilean", key: "Zilean"})
Repo.insert!(%Champion{id: 27, name: "Singed", key: "Singed"})
Repo.insert!(%Champion{id: 28, name: "Evelynn", key: "Evelynn"})
Repo.insert!(%Champion{id: 29, name: "Twitch", key: "Twitch"})
Repo.insert!(%Champion{id: 30, name: "Karthus", key: "Karthus"})
Repo.insert!(%Champion{id: 31, name: "Cho'Gath", key: "Chogath"})
Repo.insert!(%Champion{id: 32, name: "Amumu", key: "Amumu"})
Repo.insert!(%Champion{id: 33, name: "Rammus", key: "Rammus"})
Repo.insert!(%Champion{id: 34, name: "Anivia", key: "Anivia"})
Repo.insert!(%Champion{id: 35, name: "Shaco", key: "Shaco"})
Repo.insert!(%Champion{id: 36, name: "Dr. Mundo", key: "DrMundo"})
Repo.insert!(%Champion{id: 37, name: "Sona", key: "Sona"})
Repo.insert!(%Champion{id: 38, name: "Kassadin", key: "Kassadin"})
Repo.insert!(%Champion{id: 39, name: "Irelia", key: "Irelia"})
Repo.insert!(%Champion{id: 40, name: "Janna", key: "Janna"})
Repo.insert!(%Champion{id: 41, name: "Gangplank", key: "Gangplank"})
Repo.insert!(%Champion{id: 42, name: "Corki", key: "Corki"})
Repo.insert!(%Champion{id: 43, name: "Karma", key: "Karma"})
Repo.insert!(%Champion{id: 44, name: "Taric", key: "Taric"})
Repo.insert!(%Champion{id: 45, name: "Veigar", key: "Veigar"})
Repo.insert!(%Champion{id: 48, name: "Trundle", key: "Trundle"})
Repo.insert!(%Champion{id: 50, name: "Swain", key: "Swain"})
Repo.insert!(%Champion{id: 51, name: "Caitlyn", key: "Caitlyn"})
Repo.insert!(%Champion{id: 53, name: "Blitzcrank", key: "Blitzcrank"})
Repo.insert!(%Champion{id: 54, name: "Malphite", key: "Malphite"})
Repo.insert!(%Champion{id: 55, name: "Katarina", key: "Katarina"})
Repo.insert!(%Champion{id: 56, name: "Nocturne", key: "Nocturne"})
Repo.insert!(%Champion{id: 57, name: "Maokai", key: "Maokai"})
Repo.insert!(%Champion{id: 58, name: "Renekton", key: "Renekton"})
Repo.insert!(%Champion{id: 59, name: "Jarvan IV", key: "JarvanIV"})
Repo.insert!(%Champion{id: 60, name: "Elise", key: "Elise"})
Repo.insert!(%Champion{id: 61, name: "Orianna", key: "Orianna"})
Repo.insert!(%Champion{id: 62, name: "Wukong", key: "MonkeyKing"})
Repo.insert!(%Champion{id: 63, name: "Brand", key: "Brand"})
Repo.insert!(%Champion{id: 64, name: "Lee Sin", key: "LeeSin"})
Repo.insert!(%Champion{id: 67, name: "Vayne", key: "Vayne"})
Repo.insert!(%Champion{id: 68, name: "Rumble", key: "Rumble"})
Repo.insert!(%Champion{id: 69, name: "Cassiopeia", key: "Cassiopeia"})
Repo.insert!(%Champion{id: 72, name: "Skarner", key: "Skarner"})
Repo.insert!(%Champion{id: 74, name: "Heimerdinger", key: "Heimerdinger"})
Repo.insert!(%Champion{id: 75, name: "Nasus", key: "Nasus"})
Repo.insert!(%Champion{id: 76, name: "Nidalee", key: "Nidalee"})
Repo.insert!(%Champion{id: 77, name: "Udyr", key: "Udyr"})
Repo.insert!(%Champion{id: 78, name: "Poppy", key: "Poppy"})
Repo.insert!(%Champion{id: 79, name: "Gragas", key: "Gragas"})
Repo.insert!(%Champion{id: 80, name: "Pantheon", key: "Pantheon"})
Repo.insert!(%Champion{id: 81, name: "Ezreal", key: "Ezreal"})
Repo.insert!(%Champion{id: 82, name: "Mordekaiser", key: "Mordekaiser"})
Repo.insert!(%Champion{id: 83, name: "Yorick", key: "Yorick"})
Repo.insert!(%Champion{id: 84, name: "Akali", key: "Akali"})
Repo.insert!(%Champion{id: 85, name: "Kennen", key: "Kennen"})
Repo.insert!(%Champion{id: 86, name: "Garen", key: "Garen"})
Repo.insert!(%Champion{id: 89, name: "Leona", key: "Leona"})
Repo.insert!(%Champion{id: 90, name: "Malzahar", key: "Malzahar"})
Repo.insert!(%Champion{id: 91, name: "Talon", key: "Talon"})
Repo.insert!(%Champion{id: 92, name: "Riven", key: "Riven"})
Repo.insert!(%Champion{id: 96, name: "Kog'Maw", key: "KogMaw"})
Repo.insert!(%Champion{id: 98, name: "Shen", key: "Shen"})
Repo.insert!(%Champion{id: 99, name: "Lux", key: "Lux"})
Repo.insert!(%Champion{id: 101, name: "Xerath", key: "Xerath"})
Repo.insert!(%Champion{id: 102, name: "Shyvana", key: "Shyvana"})
Repo.insert!(%Champion{id: 103, name: "Ahri", key: "Ahri"})
Repo.insert!(%Champion{id: 104, name: "Graves", key: "Graves"})
Repo.insert!(%Champion{id: 105, name: "Fizz", key: "Fizz"})
Repo.insert!(%Champion{id: 106, name: "Volibear", key: "Volibear"})
Repo.insert!(%Champion{id: 107, name: "Rengar", key: "Rengar"})
Repo.insert!(%Champion{id: 110, name: "Varus", key: "Varus"})
Repo.insert!(%Champion{id: 111, name: "Nautilus", key: "Nautilus"})
Repo.insert!(%Champion{id: 112, name: "Viktor", key: "Viktor"})
Repo.insert!(%Champion{id: 113, name: "Sejuani", key: "Sejuani"})
Repo.insert!(%Champion{id: 114, name: "Fiora", key: "Fiora"})
Repo.insert!(%Champion{id: 115, name: "Ziggs", key: "Ziggs"})
Repo.insert!(%Champion{id: 117, name: "Lulu", key: "Lulu"})
Repo.insert!(%Champion{id: 119, name: "Draven", key: "Draven"})
Repo.insert!(%Champion{id: 120, name: "Hecarim", key: "Hecarim"})
Repo.insert!(%Champion{id: 121, name: "Kha'Zix", key: "Khazix"})
Repo.insert!(%Champion{id: 122, name: "Darius", key: "Darius"})
Repo.insert!(%Champion{id: 126, name: "Jayce", key: "Jayce"})
Repo.insert!(%Champion{id: 127, name: "Lissandra", key: "Lissandra"})
Repo.insert!(%Champion{id: 131, name: "Diana", key: "Diana"})
Repo.insert!(%Champion{id: 133, name: "Quinn", key: "Quinn"})
Repo.insert!(%Champion{id: 134, name: "Syndra", key: "Syndra"})
Repo.insert!(%Champion{id: 136, name: "Aurelion Sol", key: "AurelionSol"})
Repo.insert!(%Champion{id: 141, name: "Kayn", key: "Kayn"})
Repo.insert!(%Champion{id: 142, name: "Zoe", key: "Zoe"})
Repo.insert!(%Champion{id: 143, name: "Zyra", key: "Zyra"})
Repo.insert!(%Champion{id: 145, name: "Kai'Sa", key: "Kaisa"})
Repo.insert!(%Champion{id: 150, name: "Gnar", key: "Gnar"})
Repo.insert!(%Champion{id: 154, name: "Zac", key: "Zac"})
Repo.insert!(%Champion{id: 157, name: "Yasuo", key: "Yasuo"})
Repo.insert!(%Champion{id: 161, name: "Vel'Koz", key: "Velkoz"})
Repo.insert!(%Champion{id: 163, name: "Taliyah", key: "Taliyah"})
Repo.insert!(%Champion{id: 164, name: "Camille", key: "Camille"})
Repo.insert!(%Champion{id: 201, name: "Braum", key: "Braum"})
Repo.insert!(%Champion{id: 202, name: "Jhin", key: "Jhin"})
Repo.insert!(%Champion{id: 203, name: "Kindred", key: "Kindred"})
Repo.insert!(%Champion{id: 222, name: "Jinx", key: "Jinx"})
Repo.insert!(%Champion{id: 223, name: "Tahm Kench", key: "TahmKench"})
Repo.insert!(%Champion{id: 235, name: "Senna", key: "Senna"})
Repo.insert!(%Champion{id: 236, name: "Lucian", key: "Lucian"})
Repo.insert!(%Champion{id: 238, name: "Zed", key: "Zed"})
Repo.insert!(%Champion{id: 240, name: "Kled", key: "Kled"})
Repo.insert!(%Champion{id: 245, name: "Ekko", key: "Ekko"})
Repo.insert!(%Champion{id: 246, name: "Qiyana", key: "Qiyana"})
Repo.insert!(%Champion{id: 254, name: "Vi", key: "Vi"})
Repo.insert!(%Champion{id: 266, name: "Aatrox", key: "Aatrox"})
Repo.insert!(%Champion{id: 267, name: "Nami", key: "Nami"})
Repo.insert!(%Champion{id: 268, name: "Azir", key: "Azir"})
Repo.insert!(%Champion{id: 350, name: "Yuumi", key: "Yuumi"})
Repo.insert!(%Champion{id: 412, name: "Thresh", key: "Thresh"})
Repo.insert!(%Champion{id: 420, name: "Illaoi", key: "Illaoi"})
Repo.insert!(%Champion{id: 421, name: "Rek'Sai", key: "RekSai"})
Repo.insert!(%Champion{id: 427, name: "Ivern", key: "Ivern"})
Repo.insert!(%Champion{id: 429, name: "Kalista", key: "Kalista"})
Repo.insert!(%Champion{id: 432, name: "Bard", key: "Bard"})
Repo.insert!(%Champion{id: 497, name: "Rakan", key: "Rakan"})
Repo.insert!(%Champion{id: 498, name: "Xayah", key: "Xayah"})
Repo.insert!(%Champion{id: 516, name: "Ornn", key: "Ornn"})
Repo.insert!(%Champion{id: 517, name: "Sylas", key: "Sylas"})
Repo.insert!(%Champion{id: 518, name: "Neeko", key: "Neeko"})
Repo.insert!(%Champion{id: 523, name: "Aphelios", key: "Aphelios"})
Repo.insert!(%Champion{id: 555, name: "Pyke", key: "Pyke"})
Repo.insert!(%Champion{id: 875, name: "Sett", key: "Sett"})
Repo.insert!(%Champion{id: 876, name: "Lillia", key: "Lillia"})
Repo.insert!(%Champion{id: 777, name: "Yone", key: "Yone"})
Repo.insert!(%Champion{id: 360, name: "Samira", key: "Samira"})
Repo.insert!(%Champion{id: 147, name: "Seraphine", key: "Seraphine"})
Repo.insert!(%Champion{id: 526, name: "Rell", key: "Rell"})
Repo.insert!(%Champion{id: 234, name: "Viego", key: "Viego"})
Repo.insert!(%Champion{id: 887, name: "Gwen", key: "Gwen"})
Repo.insert!(%Champion{id: 166, name: "Akshan", key: "Akshan"})

# Items
Repo.insert!(%Item{id: 1001, name: "Boots"})
Repo.insert!(%Item{id: 1004, name: "Faerie Charm"})
Repo.insert!(%Item{id: 1006, name: "Rejuvenation Bead"})
Repo.insert!(%Item{id: 1011, name: "Giant's Belt"})
Repo.insert!(%Item{id: 1018, name: "Cloak of Agility"})
Repo.insert!(%Item{id: 1026, name: "Blasting Wand"})
Repo.insert!(%Item{id: 1027, name: "Sapphire Crystal"})
Repo.insert!(%Item{id: 1028, name: "Ruby Crystal"})
Repo.insert!(%Item{id: 1029, name: "Cloth Armor"})
Repo.insert!(%Item{id: 1031, name: "Chain Vest"})
Repo.insert!(%Item{id: 1033, name: "Null-Magic Mantle"})
Repo.insert!(%Item{id: 1035, name: "Emberknife"})
Repo.insert!(%Item{id: 1036, name: "Long Sword"})
Repo.insert!(%Item{id: 1037, name: "Pickaxe"})
Repo.insert!(%Item{id: 1038, name: "B. F. Sword"})
Repo.insert!(%Item{id: 1039, name: "Hailblade"})
Repo.insert!(%Item{id: 1042, name: "Dagger"})
Repo.insert!(%Item{id: 1043, name: "Recurve Bow"})
Repo.insert!(%Item{id: 1052, name: "Amplifying Tome"})
Repo.insert!(%Item{id: 1053, name: "Vampiric Scepter"})
Repo.insert!(%Item{id: 1054, name: "Doran's Shield"})
Repo.insert!(%Item{id: 1055, name: "Doran's Blade"})
Repo.insert!(%Item{id: 1056, name: "Doran's Ring"})
Repo.insert!(%Item{id: 1057, name: "Negatron Cloak"})
Repo.insert!(%Item{id: 1058, name: "Needlessly Large Rod"})
Repo.insert!(%Item{id: 1082, name: "Dark Seal"})
Repo.insert!(%Item{id: 1083, name: "Cull"})
Repo.insert!(%Item{id: 2003, name: "Health Potion"})
Repo.insert!(%Item{id: 2010, name: "Total Biscuit of Everlasting Will"})
Repo.insert!(%Item{id: 2015, name: "Kircheis Shard"})
Repo.insert!(%Item{id: 2031, name: "Refillable Potion"})
Repo.insert!(%Item{id: 2033, name: "Corrupting Potion"})
Repo.insert!(%Item{id: 2051, name: "Guardian's Horn"})
Repo.insert!(%Item{id: 2052, name: "Poro-Snax"})
Repo.insert!(%Item{id: 2055, name: "Control Ward"})
Repo.insert!(%Item{id: 2065, name: "Shurelya's Battlesong"})
Repo.insert!(%Item{id: 2138, name: "Elixir of Iron"})
Repo.insert!(%Item{id: 2139, name: "Elixir of Sorcery"})
Repo.insert!(%Item{id: 2140, name: "Elixir of Wrath"})
Repo.insert!(%Item{id: 2403, name: "Minion Dematerializer"})
Repo.insert!(%Item{id: 2419, name: "Commencing Stopwatch"})
Repo.insert!(%Item{id: 2420, name: "Stopwatch"})
Repo.insert!(%Item{id: 2421, name: "Broken Stopwatch"})
Repo.insert!(%Item{id: 2422, name: "Slightly Magical Footwear"})
Repo.insert!(%Item{id: 2423, name: "Perfectly Timed Stopwatch"})
Repo.insert!(%Item{id: 2424, name: "Broken Stopwatch"})
Repo.insert!(%Item{id: 3001, name: "Abyssal Mask"})
Repo.insert!(%Item{id: 3003, name: "Archangel's Staff"})
Repo.insert!(%Item{id: 3004, name: "Manamune"})
Repo.insert!(%Item{id: 3006, name: "Berserker's Greaves"})
Repo.insert!(%Item{id: 3009, name: "Boots of Swiftness"})
Repo.insert!(%Item{id: 3011, name: "Chemtech Putrifier"})
Repo.insert!(%Item{id: 3020, name: "Sorcerer's Shoes"})
Repo.insert!(%Item{id: 3024, name: "Glacial Buckler"})
Repo.insert!(%Item{id: 3026, name: "Guardian Angel"})
Repo.insert!(%Item{id: 3031, name: "Infinity Edge"})
Repo.insert!(%Item{id: 3033, name: "Mortal Reminder"})
Repo.insert!(%Item{id: 3035, name: "Last Whisper"})
Repo.insert!(%Item{id: 3036, name: "Lord Dominik's Regards"})
Repo.insert!(%Item{id: 3040, name: "Seraph's Embrace"})
Repo.insert!(%Item{id: 3041, name: "Mejai's Soulstealer"})
Repo.insert!(%Item{id: 3042, name: "Muramana"})
Repo.insert!(%Item{id: 3044, name: "Phage"})
Repo.insert!(%Item{id: 3046, name: "Phantom Dancer"})
Repo.insert!(%Item{id: 3047, name: "Plated Steelcaps"})
Repo.insert!(%Item{id: 3050, name: "Zeke's Convergence"})
Repo.insert!(%Item{id: 3051, name: "Hearthbound Axe"})
Repo.insert!(%Item{id: 3053, name: "Sterak's Gage"})
Repo.insert!(%Item{id: 3057, name: "Sheen"})
Repo.insert!(%Item{id: 3065, name: "Spirit Visage"})
Repo.insert!(%Item{id: 3066, name: "Winged Moonplate"})
Repo.insert!(%Item{id: 3067, name: "Kindlegem"})
Repo.insert!(%Item{id: 3068, name: "Sunfire Aegis"})
Repo.insert!(%Item{id: 3070, name: "Tear of the Goddess"})
Repo.insert!(%Item{id: 3071, name: "Black Cleaver"})
Repo.insert!(%Item{id: 3072, name: "Bloodthirster"})
Repo.insert!(%Item{id: 3074, name: "Ravenous Hydra"})
Repo.insert!(%Item{id: 3075, name: "Thornmail"})
Repo.insert!(%Item{id: 3076, name: "Bramble Vest"})
Repo.insert!(%Item{id: 3077, name: "Tiamat"})
Repo.insert!(%Item{id: 3078, name: "Trinity Force"})
Repo.insert!(%Item{id: 3082, name: "Warden's Mail"})
Repo.insert!(%Item{id: 3083, name: "Warmog's Armor"})
Repo.insert!(%Item{id: 3085, name: "Runaan's Hurricane"})
Repo.insert!(%Item{id: 3086, name: "Zeal"})
Repo.insert!(%Item{id: 3089, name: "Rabadon's Deathcap"})
Repo.insert!(%Item{id: 3091, name: "Wit's End"})
Repo.insert!(%Item{id: 3094, name: "Rapid Firecannon"})
Repo.insert!(%Item{id: 3095, name: "Stormrazor"})
Repo.insert!(%Item{id: 3100, name: "Lich Bane"})
Repo.insert!(%Item{id: 3102, name: "Banshee's Veil"})
Repo.insert!(%Item{id: 3105, name: "Aegis of the Legion"})
Repo.insert!(%Item{id: 3107, name: "Redemption"})
Repo.insert!(%Item{id: 3108, name: "Fiendish Codex"})
Repo.insert!(%Item{id: 3109, name: "Knight's Vow"})
Repo.insert!(%Item{id: 3110, name: "Frozen Heart"})
Repo.insert!(%Item{id: 3111, name: "Mercury's Treads"})
Repo.insert!(%Item{id: 3112, name: "Guardian's Orb"})
Repo.insert!(%Item{id: 3113, name: "Aether Wisp"})
Repo.insert!(%Item{id: 3114, name: "Forbidden Idol"})
Repo.insert!(%Item{id: 3115, name: "Nashor's Tooth"})
Repo.insert!(%Item{id: 3116, name: "Rylai's Crystal Scepter"})
Repo.insert!(%Item{id: 3117, name: "Mobility Boots"})
Repo.insert!(%Item{id: 3123, name: "Executioner's Calling"})
Repo.insert!(%Item{id: 3124, name: "Guinsoo's Rageblade"})
Repo.insert!(%Item{id: 3133, name: "Caulfield's Warhammer"})
Repo.insert!(%Item{id: 3134, name: "Serrated Dirk"})
Repo.insert!(%Item{id: 3135, name: "Void Staff"})
Repo.insert!(%Item{id: 3139, name: "Mercurial Scimitar"})
Repo.insert!(%Item{id: 3140, name: "Quicksilver Sash"})
Repo.insert!(%Item{id: 3142, name: "Youmuu's Ghostblade"})
Repo.insert!(%Item{id: 3143, name: "Randuin's Omen"})
Repo.insert!(%Item{id: 3145, name: "Hextech Alternator"})
Repo.insert!(%Item{id: 3152, name: "Hextech Rocketbelt"})
Repo.insert!(%Item{id: 3153, name: "Blade of The Ruined King"})
Repo.insert!(%Item{id: 3155, name: "Hexdrinker"})
Repo.insert!(%Item{id: 3156, name: "Maw of Malmortius"})
Repo.insert!(%Item{id: 3157, name: "Zhonya's Hourglass"})
Repo.insert!(%Item{id: 3158, name: "Ionian Boots of Lucidity"})
Repo.insert!(%Item{id: 3165, name: "Morellonomicon"})
Repo.insert!(%Item{id: 3177, name: "Guardian's Blade"})
Repo.insert!(%Item{id: 3179, name: "Umbral Glaive"})
Repo.insert!(%Item{id: 3181, name: "Hullbreaker"})
Repo.insert!(%Item{id: 3184, name: "Guardian's Hammer"})
Repo.insert!(%Item{id: 3190, name: "Locket of the Iron Solari"})
Repo.insert!(%Item{id: 3191, name: "Seeker's Armguard"})
Repo.insert!(%Item{id: 3193, name: "Gargoyle Stoneplate"})
Repo.insert!(%Item{id: 3211, name: "Spectre's Cowl"})
Repo.insert!(%Item{id: 3222, name: "Mikael's Blessing"})
Repo.insert!(%Item{id: 3330, name: "Scarecrow Effigy"})
Repo.insert!(%Item{id: 3340, name: "Stealth Ward"})
Repo.insert!(%Item{id: 3363, name: "Farsight Alteration"})
Repo.insert!(%Item{id: 3364, name: "Oracle Lens"})
Repo.insert!(%Item{id: 3400, name: "Your Cut"})
Repo.insert!(%Item{id: 3504, name: "Ardent Censer"})
Repo.insert!(%Item{id: 3508, name: "Essence Reaver"})
Repo.insert!(%Item{id: 3513, name: "Eye of the Herald"})
Repo.insert!(%Item{id: 3599, name: "Kalista's Black Spear"})
Repo.insert!(%Item{id: 3600, name: "Kalista's Black Spear"})
Repo.insert!(%Item{id: 3742, name: "Dead Man's Plate"})
Repo.insert!(%Item{id: 3748, name: "Titanic Hydra"})
Repo.insert!(%Item{id: 3801, name: "Crystalline Bracer"})
Repo.insert!(%Item{id: 3802, name: "Lost Chapter"})
Repo.insert!(%Item{id: 3814, name: "Edge of Night"})
Repo.insert!(%Item{id: 3850, name: "Spellthief's Edge"})
Repo.insert!(%Item{id: 3851, name: "Frostfang"})
Repo.insert!(%Item{id: 3853, name: "Shard of True Ice"})
Repo.insert!(%Item{id: 3854, name: "Steel Shoulderguards"})
Repo.insert!(%Item{id: 3855, name: "Runesteel Spaulders"})
Repo.insert!(%Item{id: 3857, name: "Pauldrons of Whiterock"})
Repo.insert!(%Item{id: 3858, name: "Relic Shield"})
Repo.insert!(%Item{id: 3859, name: "Targon's Buckler"})
Repo.insert!(%Item{id: 3860, name: "Bulwark of the Mountain"})
Repo.insert!(%Item{id: 3862, name: "Spectral Sickle"})
Repo.insert!(%Item{id: 3863, name: "Harrowing Crescent"})
Repo.insert!(%Item{id: 3864, name: "Black Mist Scythe"})
Repo.insert!(%Item{id: 3916, name: "Oblivion Orb"})
Repo.insert!(%Item{id: 4005, name: "Imperial Mandate"})
Repo.insert!(%Item{id: 4401, name: "Force of Nature"})
Repo.insert!(%Item{id: 4403, name: "The Golden Spatula"})
Repo.insert!(%Item{id: 4628, name: "Horizon Focus"})
Repo.insert!(%Item{id: 4629, name: "Cosmic Drive"})
Repo.insert!(%Item{id: 4630, name: "Blighting Jewel"})
Repo.insert!(%Item{id: 4632, name: "Verdant Barrier"})
Repo.insert!(%Item{id: 4633, name: "Riftmaker"})
Repo.insert!(%Item{id: 4635, name: "Leeching Leer"})
Repo.insert!(%Item{id: 4636, name: "Night Harvester"})
Repo.insert!(%Item{id: 4637, name: "Demonic Embrace"})
Repo.insert!(%Item{id: 4638, name: "Watchful Wardstone"})
Repo.insert!(%Item{id: 4642, name: "Bandleglass Mirror"})
Repo.insert!(%Item{id: 4643, name: "Vigilant Wardstone"})
Repo.insert!(%Item{id: 6029, name: "Ironspike Whip"})
Repo.insert!(%Item{id: 6035, name: "Silvermere Dawn"})
Repo.insert!(%Item{id: 6333, name: "Death's Dance"})
Repo.insert!(%Item{id: 6609, name: "Chempunk Chainsword"})
Repo.insert!(%Item{id: 6616, name: "Staff of Flowing Water"})
Repo.insert!(%Item{id: 6617, name: "Moonstone Renewer"})
Repo.insert!(%Item{id: 6630, name: "Goredrinker"})
Repo.insert!(%Item{id: 6631, name: "Stridebreaker"})
Repo.insert!(%Item{id: 6632, name: "Divine Sunderer"})
Repo.insert!(%Item{id: 6653, name: "Liandry's Anguish"})
Repo.insert!(%Item{id: 6655, name: "Luden's Tempest"})
Repo.insert!(%Item{id: 6656, name: "Everfrost"})
Repo.insert!(%Item{id: 6660, name: "Bami's Cinder"})
Repo.insert!(%Item{id: 6662, name: "Frostfire Gauntlet"})
Repo.insert!(%Item{id: 6664, name: "Turbo Chemtank"})
Repo.insert!(%Item{id: 6670, name: "Noonquiver"})
Repo.insert!(%Item{id: 6671, name: "Galeforce"})
Repo.insert!(%Item{id: 6672, name: "Kraken Slayer"})
Repo.insert!(%Item{id: 6673, name: "Immortal Shieldbow"})
Repo.insert!(%Item{id: 6675, name: "Navori Quickblades"})
Repo.insert!(%Item{id: 6676, name: "The Collector"})
Repo.insert!(%Item{id: 6677, name: "Rageknife"})
Repo.insert!(%Item{id: 6691, name: "Duskblade of Draktharr"})
Repo.insert!(%Item{id: 6692, name: "Eclipse"})
Repo.insert!(%Item{id: 6693, name: "Prowler's Claw"})
Repo.insert!(%Item{id: 6694, name: "Serylda's Grudge"})
Repo.insert!(%Item{id: 6695, name: "Serpent's Fang"})
Repo.insert!(%Item{id: 8001, name: "Anathema's Chains"})
