defmodule League.Tags do
  alias League.Stats

  def get_mid_champions do
    get_champions([
      "Aatrox",
      "Ahri",
      "Akali",
      "Akshan",
      "Anivia",
      "Annie",
      "Aurelion Sol",
      "Azir",
      "Cassiopeia",
      "Corki",
      "Diana",
      "Ekko",
      "Fizz",
      "Galio",
      "Garen",
      "Graves",
      "Irelia",
      "Jayce",
      "Kassadin",
      "Katarina",
      "LeBlanc",
      "Lee Sin",
      "Lissandra",
      "Lucian",
      "Lux",
      "Malphite",
      "Malzahar",
      "Orianna",
      "Pantheon",
      "Qiyana",
      "Renekton",
      "Rumble",
      "Ryze",
      "Sett",
      "Sylas",
      "Syndra",
      "Talon",
      "Twisted Fate",
      "Veigar",
      "Viego",
      "Viktor",
      "Vladimir",
      "Xerath",
      "Yasuo",
      "Yone",
      "Zed",
      "Ziggs",
      "Zoe"
    ])
  end

  def get_top_champions do
    get_champions([
      "Aatrox",
      "Akali",
      "Akshan",
      "Camille",
      "Cassiopeia",
      "Cho'Gath",
      "Darius",
      "Dr. Mundo",
      "Fiora",
      "Gangplank",
      "Garen",
      "Gnar",
      "Gragas",
      "Gwen",
      "Heimerdinger",
      "Illaoi",
      "Irelia",
      "Jarvan IV",
      "Jax",
      "Jayce",
      "Kayle",
      "Kennen",
      "Kled",
      "Lee Sin",
      "Lillia",
      "Lucian",
      "Malphite",
      "Maokai",
      "Mordekaiser",
      "Nasus",
      "Ornn",
      "Pantheon",
      "Poppy",
      "Quinn",
      "Renekton",
      "Rengar",
      "Riven",
      "Rumble",
      "Ryze",
      "Sett",
      "Shen",
      "Singed",
      "Sion",
      "Sylas",
      "Tahm Kench",
      "Teemo",
      "Trundle",
      "Tryndamere",
      "Urgot",
      "Vayne",
      "Viego",
      "Vladimir",
      "Volibear",
      "Warwick",
      "Wukong",
      "Yasuo",
      "Yone",
      "Yorick",
      "Zac"
    ])
  end

  defp get_champions(names) do
    Enum.filter(Stats.list_champions(), &Enum.member?(names, &1.name))
  end
end
